{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.funczz",
    "module": "sam",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sam-0.2.0.jar",
          "url": "sam-0.2.0.jar",
          "size": 5985,
          "sha512": "2d5b26936c3de56105b94d8561986897e42f599bb1001ff16f7ad063f2ddbf68b4e0f106c2af4a0d357435f08b31b5c5942360e2c8e1344918b6ef588173ad89",
          "sha256": "24e84c76637e388955dcce54658397c0cc1a26fb9160fea103f942bc62ac3036",
          "sha1": "672af2e9f7a4692ef68c0115fe255e991ebfa7c0",
          "md5": "28bc6360a119f3d9121deff69629215b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "sam-0.2.0.jar",
          "url": "sam-0.2.0.jar",
          "size": 5985,
          "sha512": "2d5b26936c3de56105b94d8561986897e42f599bb1001ff16f7ad063f2ddbf68b4e0f106c2af4a0d357435f08b31b5c5942360e2c8e1344918b6ef588173ad89",
          "sha256": "24e84c76637e388955dcce54658397c0cc1a26fb9160fea103f942bc62ac3036",
          "sha1": "672af2e9f7a4692ef68c0115fe255e991ebfa7c0",
          "md5": "28bc6360a119f3d9121deff69629215b"
        }
      ]
    }
  ]
}
