{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.funczz",
    "module": "sam",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "xriuyspbqngrvb6ojd3mck6xam"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "sam-0.1.0.jar",
          "url": "sam-0.1.0.jar",
          "size": 13567,
          "sha512": "6ed5c8490304c40e1ae90f47e3ede9fe7282591d659d9d02702fedccb71e654cb1c1b222cc82603c67da215f3aa3dbfa3753654e08643e0f019a38fbf190a279",
          "sha256": "8eb7bc4f1a9b138069f5804ae03ce5f77b588786cac4245b6ab1ec726cd7a6ce",
          "sha1": "6fefa4a92a4cc78b90cbf2647fb60265bc607642",
          "md5": "840d4f60364322cdd50649928460a4c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "sam-0.1.0.jar",
          "url": "sam-0.1.0.jar",
          "size": 13567,
          "sha512": "6ed5c8490304c40e1ae90f47e3ede9fe7282591d659d9d02702fedccb71e654cb1c1b222cc82603c67da215f3aa3dbfa3753654e08643e0f019a38fbf190a279",
          "sha256": "8eb7bc4f1a9b138069f5804ae03ce5f77b588786cac4245b6ab1ec726cd7a6ce",
          "sha1": "6fefa4a92a4cc78b90cbf2647fb60265bc607642",
          "md5": "840d4f60364322cdd50649928460a4c7"
        }
      ]
    }
  ]
}
